We perform equal weights + risk parity + CVaR approaches to test strength of these strategies during dynamic market conditions. We test for both generic market conditions as well as (very) volatile downturns.

The goal is to minimize tail risk whilst attempting to minimize the impact on general returns / sharpe ratio.

In [71]:
import pandas as pd
import numpy as np
from pathlib import Path
import plotly.graph_objects as go
from scipy.stats import multivariate_normal, norm

snp = pd.read_csv(Path.cwd().parent / "data" / "OHCL" / "snp500.csv", index_col=1)
china = pd.read_csv(Path.cwd().parent / "data" / "OHCL" / "china_transformed.csv", index_col=1).reset_index()
em = pd.read_csv(Path.cwd().parent / "data" / "OHCL" / "emerging_markets.csv", index_col=1)
gold = pd.read_csv(Path.cwd().parent / "data" / "OHCL" / "gold.csv", index_col=1)
india = pd.read_csv(Path.cwd().parent / "data" / "OHCL" / "india.csv", index_col=1)
mscieurope = pd.read_csv(Path.cwd().parent / "data" / "OHCL" / "msci_europe.csv", index_col=1)
smallcapeurope = pd.read_csv(Path.cwd().parent / "data" / "OHCL" / "small_cap_europe.csv", index_col=1)

labels = ["snp", "china", "em", "gold", "india", "mscieurope", "smallcapeurope"]
dfs = [snp, china, em, gold, india, mscieurope, smallcapeurope]

def transform_date(date):
    parts = date.split(' ')
    if len(parts) == 1:
        return date
    return parts[0]

for df in dfs:
    df["Date"] = df["Date"].apply(transform_date)

china

date_sets = [set(df["Date"]) for df in dfs]

# Find the intersection of all date sets
common_dates = set.intersection(*date_sets)

# Filter each DataFrame to include only common dates
filtered_dfs = [df[df["Date"].isin(common_dates)] for df in dfs]

#for df in dfs:
#    df["Date"] = df["Date"].apply(pd.to_datetime)

#print(filtered_dfs[0].iloc[0:90]["Date"].values)

In [72]:

N = len(filtered_dfs)
T = len(filtered_dfs[0]) - 1

returns_all = np.empty((T, N))
sorted_returns_all = np.empty((T, N))
for i, df in enumerate(filtered_dfs):
    returns = df["Close"].pct_change().values[1:]
    returns_all[:, i] = returns
    sorted_returns_all[:, i] = sorted(returns)

all_dates = filtered_dfs[0]["Date"].values[1:]

In [73]:
def perform_validation(w, validation_data):
    # validation data is shape (T, N)
    
    # perform metrics
    total_return = validation_data @ w # shape (T,)
    cumulative_returns = np.cumprod(total_return + 1) - 1
    risk_free = 0.0
    std = np.std(total_return)
    downside_std = np.std(total_return[total_return > 0])
    sharpe = (255 * np.mean(total_return) - risk_free) / (np.sqrt(255) * std)
    sortino = (255 * np.mean(total_return) - risk_free) / (np.sqrt(255) * downside_std)    

    alpha = 0.10

    var_alpha = np.quantile(total_return, alpha)
    cvar = total_return[total_return <= var_alpha].mean()
    mean_return = np.mean(total_return)
    return var_alpha, cvar, sharpe, sortino, cumulative_returns, mean_return

In [80]:
import tensorflow as tf

# train weights
alpha = 0.05   # tail probability for CVaR
lambda_ = 1.1  # CVaR penalty
learning_rate = 0.01
gamma = 0.035
num_steps = 2000
beta = 0.1 # penalty volatility

def gradient(train_data, cov):

    # train data: (T,N)
    w = tf.Variable(tf.ones([N], dtype=tf.float32) / N)
    t = tf.Variable(0.0, dtype=tf.float32)  # VaR threshold

    optimizer = tf.keras.optimizers.Adam(learning_rate)

    X_tf = tf.convert_to_tensor(train_data, dtype=tf.float32) # (T,N)
    cov_tf = tf.convert_to_tensor(cov, dtype=tf.float32)  # shape (N, N)

    for step in range(num_steps):
        with tf.GradientTape() as tape:
            # enforce sum-to-1 via softmax
            w_normalized = tf.nn.softmax(w)
            w_col = tf.reshape(w_normalized, [N, 1])  # shape (N,1)

            # portfolio returns
            portfolio_returns = tf.matmul(X_tf, tf.reshape(w_col, [-1,1])) # (T)
            losses = -portfolio_returns
            cvar = t + (1 / (1 - alpha)) * tf.reduce_mean(tf.nn.relu(losses - t))
            
            # portfolio variance
            portfolio_variance = tf.squeeze(tf.transpose(w_col) @ cov_tf @ w_col)

            objective = (
                -(tf.reduce_mean(portfolio_returns) - lambda_ * cvar)
                + beta * portfolio_variance
            )

        # compute gradients
        grads = tape.gradient(objective, [w, t])
        optimizer.apply_gradients(zip(grads, [w, t]))

        if step % 200 == 0:
            print(f"Step {step}: objective = {-objective.numpy():.6f}")

    # after the optimization loop
    optimal_w = tf.nn.softmax(w).numpy()
    return optimal_w
    
def gradient_risk_parity(cov):

    # train data: (T,N)
    w = tf.Variable(tf.ones([N], dtype=tf.float32) / N)

    optimizer = tf.keras.optimizers.Adam(learning_rate)
    cov_tf = tf.convert_to_tensor(cov, dtype=tf.float32)  # shape (N, N)

    for step in range(num_steps):
        with tf.GradientTape() as tape:
            # enforce sum-to-1 via softmax
            w_normalized = tf.nn.softmax(w)
            w_col = tf.reshape(w_normalized, [N, 1])  # shape (N,1)
            
            # portfolio variance
            portfolio_variance = tf.squeeze(tf.transpose(w_col) @ cov_tf @ w_col)

            marginal = cov_tf @ w_col
            risk_contrib = w_col * marginal

            risk_parity_target = portfolio_variance / N
            objective = tf.reduce_sum((risk_contrib - risk_parity_target)**2)


        # compute gradients
        grads = tape.gradient(objective, [w])
        optimizer.apply_gradients(zip(grads, [w]))

        if step % 200 == 0:
            print(f"Step {step}: objective = {-objective.numpy():.6f}")

    # after the optimization loop
    optimal_w = tf.nn.softmax(w).numpy()
    return optimal_w

def gradient_reduced(train_data, cov):

    # train data: (T,N)
    w = tf.Variable(tf.ones([N], dtype=tf.float32) / N)
    t = tf.Variable(0.0, dtype=tf.float32)  # VaR threshold

    optimizer = tf.keras.optimizers.Adam(learning_rate)

    X_tf = tf.convert_to_tensor(train_data, dtype=tf.float32) # (T,N)
    cov_tf = tf.convert_to_tensor(cov, dtype=tf.float32)  # shape (N, N)

    for step in range(num_steps):
        with tf.GradientTape() as tape:
            # enforce sum-to-1 via softmax
            w_normalized = tf.nn.softmax(w)
            w_col = tf.reshape(w_normalized, [N, 1])  # shape (N,1)

            # portfolio returns
            portfolio_returns = tf.matmul(X_tf, tf.reshape(w_col, [-1,1])) # (T)
            losses = -portfolio_returns
            cvar = t + (1 / (1 - alpha)) * tf.reduce_mean(tf.nn.relu(losses - t))

            objective = -(tf.reduce_mean(portfolio_returns) - lambda_ * cvar)

        # compute gradients
        grads = tape.gradient(objective, [w, t])
        optimizer.apply_gradients(zip(grads, [w, t]))

        if step % 200 == 0:
            print(f"Step {step}: objective = {-objective.numpy():.6f}")

    # after the optimization loop
    optimal_w = tf.nn.softmax(w).numpy()
    return optimal_w

In [78]:
# run

def select_random_block(returns, block_size):
    n = len(returns)
    lst = list(range(n))
    chosen_idx = np.random.choice(lst)
    while not (block_size < chosen_idx < n - block_size):
        chosen_idx = np.random.choice(n)
    selected_train_data = returns[chosen_idx - block_size : chosen_idx]
    selected_validation_data = returns[chosen_idx : chosen_idx + block_size]
    return selected_train_data, selected_validation_data

def block_bootstrap(n_bootstrap, returns_all):

    sharpes_w_opt= []
    sharpes_w_rp = []
    sharpes_w_eqw = []

    mean_return_w_opt = []
    mean_return_w_rp = []
    mean_return_w_eqw = []

    sortinos_w_opt = []
    sortinos_w_rp = []
    sortinos_w_eqw = []

    vars_w_opt = []
    vars_w_rp = []
    vars_w_eqw = []

    cvars_w_opt = []
    cvars_w_rp = []
    cvars_w_eqw = []

    for _ in range(n_bootstrap):
        train_data, val_data = select_random_block(returns_all, 252)
        cov = np.cov(train_data, rowvar=False)

        w_opt = gradient(train_data, cov)
        w_rp = gradient_risk_parity(cov)

        (
            var_alpha, cvar, sharpe, sortino, cumulative_returns, mean_return
        ) = perform_validation(w_opt, val_data)

        sharpes_w_opt.append(sharpe)
        sortinos_w_opt.append(sortino)
        vars_w_opt.append(var_alpha)
        cvars_w_opt.append(cvar)
        mean_return_w_opt.append(mean_return)

        (
            var_alpha, cvar, sharpe, sortino, cumulative_returns, mean_return
        ) = perform_validation(w_rp, val_data)

        sharpes_w_rp.append(sharpe)
        sortinos_w_rp.append(sortino)
        vars_w_rp.append(var_alpha)
        cvars_w_rp.append(cvar)
        mean_return_w_rp.append(mean_return)

        (
            var_alpha, cvar, sharpe, sortino, cumulative_returns, mean_return
        ) = perform_validation(np.ones(N) / N, val_data)

        sharpes_w_eqw.append(sharpe)
        sortinos_w_eqw.append(sortino)
        vars_w_eqw.append(var_alpha)
        cvars_w_eqw.append(cvar)
        mean_return_w_eqw.append(mean_return)

    df = pd.DataFrame({
        "Sharpes": [np.mean(sharpes_w_eqw), np.mean(sharpes_w_rp), np.mean(sharpes_w_opt)],
        "Sortinos": [np.mean(sortinos_w_eqw), np.mean(sortinos_w_rp), np.mean(sortinos_w_opt)],
        "Vars": [np.mean(vars_w_eqw), np.mean(vars_w_rp), np.mean(vars_w_opt)],
        "Cvars": [np.mean(cvars_w_eqw), np.mean(cvars_w_rp), np.mean(cvars_w_opt)],
        "MeanReturn": [np.mean(mean_return_w_eqw), np.mean(mean_return_w_rp), np.mean(mean_return_w_opt)],
    }, index=["Equal weights", "Risk parity", "Return + CVaR"])

    return df

def rolling_window(window_size, stepsize, validation_size, data):
    # data is (T,N)

    sharpes_w_opt= []
    sharpes_w_rp = []
    sharpes_w_eqw = []

    mean_return_w_opt = []
    mean_return_w_rp = []
    mean_return_w_eqw = []

    sortinos_w_opt = []
    sortinos_w_rp = []
    sortinos_w_eqw = []

    vars_w_opt = []
    vars_w_rp = []
    vars_w_eqw = []

    cvars_w_opt = []
    cvars_w_rp = []
    cvars_w_eqw = []
    T, N = data.shape
    for idx in range(0, T - window_size - validation_size, stepsize):
        train_data = data[idx:idx+window_size]
        val_data = data[idx+window_size:idx+window_size+validation_size]
        cov = np.cov(train_data, rowvar=False)

        w_opt = gradient_reduced(train_data, cov)
        w_rp = gradient_risk_parity(cov)

        (
            var_alpha, cvar, sharpe, sortino, cumulative_returns, mean_return
        ) = perform_validation(w_opt, val_data)

        sharpes_w_opt.append(sharpe)
        sortinos_w_opt.append(sortino)
        vars_w_opt.append(var_alpha)
        cvars_w_opt.append(cvar)
        mean_return_w_opt.append(mean_return)

        (
            var_alpha, cvar, sharpe, sortino, cumulative_returns, mean_return
        ) = perform_validation(w_rp, val_data)

        sharpes_w_rp.append(sharpe)
        sortinos_w_rp.append(sortino)
        vars_w_rp.append(var_alpha)
        cvars_w_rp.append(cvar)
        mean_return_w_rp.append(mean_return)

        (
            var_alpha, cvar, sharpe, sortino, cumulative_returns, mean_return
        ) = perform_validation(np.ones(N) / N, val_data)

        sharpes_w_eqw.append(sharpe)
        sortinos_w_eqw.append(sortino)
        vars_w_eqw.append(var_alpha)
        cvars_w_eqw.append(cvar)
        mean_return_w_eqw.append(mean_return)

    df = pd.DataFrame({
        "Sharpes": [np.mean(sharpes_w_eqw), np.mean(sharpes_w_rp), np.mean(sharpes_w_opt)],
        "Sortinos": [np.mean(sortinos_w_eqw), np.mean(sortinos_w_rp), np.mean(sortinos_w_opt)],
        "Vars": [np.mean(vars_w_eqw), np.mean(vars_w_rp), np.mean(vars_w_opt)],
        "Cvars": [np.mean(cvars_w_eqw), np.mean(cvars_w_rp), np.mean(cvars_w_opt)],
        "MeanReturn": [np.mean(mean_return_w_eqw), np.mean(mean_return_w_rp), np.mean(mean_return_w_opt)],
    }, index=["Equal weights", "Risk parity", "Return + CVaR"])

    return df

In [81]:
df = rolling_window(
    window_size=252*2,
    stepsize=30,
    validation_size=252,
    data=returns_all
)
df

Step 0: objective = -0.003314
Step 200: objective = -0.000431
Step 400: objective = -0.000379
Step 600: objective = -0.000367
Step 800: objective = -0.000362
Step 1000: objective = -0.000359
Step 1200: objective = -0.000357
Step 1400: objective = -0.000357
Step 1600: objective = -0.000356
Step 1800: objective = -0.000359
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.003179
Step 200: objective = -0.000331
Step 400: objective = -0.000276
Step 600: objective = -0.000265
Step 800: objective = -0.000260
Step 1000: objective = -0.000260
Step 1200: objective = -0.000257
Step 1400: objective = -0.000256
Step 1600: objective = -0.000262
Step 1800: objective = -0.000255
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.003008
Step 200: objective = -0.000138
Step 400: objective = -0.000080
Step 600: objective = -0.000074
Step 800: objective = -0.000064
Step 1000: objective = -0.000060
Step 1200: objective = -0.000059
Step 1400: objective = -0.000059
Step 1600: objective = -0.000059
Step 1800: objective = -0.000058
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002680
Step 200: objective = 0.000152
Step 400: objective = 0.000193
Step 600: objective = 0.000203
Step 800: objective = 0.000208
Step 1000: objective = 0.000209
Step 1200: objective = 0.000211
Step 1400: objective = 0.000208
Step 1600: objective = 0.000212
Step 1800: objective = 0.000214
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002267
Step 200: objective = 0.000421
Step 400: objective = 0.000473
Step 600: objective = 0.000485
Step 800: objective = 0.000490
Step 1000: objective = 0.000493
Step 1200: objective = 0.000494
Step 1400: objective = 0.000496
Step 1600: objective = 0.000495
Step 1800: objective = 0.000497
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002274
Step 200: objective = 0.000493
Step 400: objective = 0.000589
Step 600: objective = 0.000606
Step 800: objective = 0.000612
Step 1000: objective = 0.000614
Step 1200: objective = 0.000616
Step 1400: objective = 0.000617
Step 1600: objective = 0.000618
Step 1800: objective = 0.000618
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002227
Step 200: objective = 0.000596
Step 400: objective = 0.000696
Step 600: objective = 0.000713
Step 800: objective = 0.000719
Step 1000: objective = 0.000722
Step 1200: objective = 0.000723
Step 1400: objective = 0.000724
Step 1600: objective = 0.000725
Step 1800: objective = 0.000726
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001750
Step 200: objective = 0.000902
Step 400: objective = 0.000945
Step 600: objective = 0.000955
Step 800: objective = 0.000959
Step 1000: objective = 0.000961
Step 1200: objective = 0.000960
Step 1400: objective = 0.000963
Step 1600: objective = 0.000963
Step 1800: objective = 0.000955
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001909
Step 200: objective = 0.000501
Step 400: objective = 0.000527
Step 600: objective = 0.000534
Step 800: objective = 0.000537
Step 1000: objective = 0.000539
Step 1200: objective = 0.000540
Step 1400: objective = 0.000539
Step 1600: objective = 0.000541
Step 1800: objective = 0.000540
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001837
Step 200: objective = 0.000601
Step 400: objective = 0.000632
Step 600: objective = 0.000640
Step 800: objective = 0.000643
Step 1000: objective = 0.000644
Step 1200: objective = 0.000645
Step 1400: objective = 0.000644
Step 1600: objective = 0.000646
Step 1800: objective = 0.000647
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001942
Step 200: objective = 0.000491
Step 400: objective = 0.000525
Step 600: objective = 0.000534
Step 800: objective = 0.000538
Step 1000: objective = 0.000540
Step 1200: objective = 0.000541
Step 1400: objective = 0.000542
Step 1600: objective = 0.000542
Step 1800: objective = 0.000542
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002186
Step 200: objective = 0.000019
Step 400: objective = 0.000040
Step 600: objective = 0.000046
Step 800: objective = 0.000048
Step 1000: objective = 0.000050
Step 1200: objective = 0.000050
Step 1400: objective = 0.000051
Step 1600: objective = 0.000051
Step 1800: objective = 0.000051
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002309
Step 200: objective = -0.000091
Step 400: objective = -0.000068
Step 600: objective = -0.000061
Step 800: objective = -0.000059
Step 1000: objective = -0.000057
Step 1200: objective = -0.000057
Step 1400: objective = -0.000056
Step 1600: objective = -0.000056
Step 1800: objective = -0.000055
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001912
Step 200: objective = 0.000431
Step 400: objective = 0.000450
Step 600: objective = 0.000456
Step 800: objective = 0.000458
Step 1000: objective = 0.000459
Step 1200: objective = 0.000459
Step 1400: objective = 0.000457
Step 1600: objective = 0.000461
Step 1800: objective = 0.000459
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001827
Step 200: objective = 0.000458
Step 400: objective = 0.000470
Step 600: objective = 0.000477
Step 800: objective = 0.000477
Step 1000: objective = 0.000479
Step 1200: objective = 0.000479
Step 1400: objective = 0.000478
Step 1600: objective = 0.000479
Step 1800: objective = 0.000478
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002140
Step 200: objective = 0.000085
Step 400: objective = 0.000094
Step 600: objective = 0.000096
Step 800: objective = 0.000097
Step 1000: objective = 0.000097
Step 1200: objective = 0.000098
Step 1400: objective = 0.000093
Step 1600: objective = 0.000098
Step 1800: objective = 0.000097
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002072
Step 200: objective = 0.000302
Step 400: objective = 0.000315
Step 600: objective = 0.000318
Step 800: objective = 0.000319
Step 1000: objective = 0.000321
Step 1200: objective = 0.000321
Step 1400: objective = 0.000321
Step 1600: objective = 0.000320
Step 1800: objective = 0.000317
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002229
Step 200: objective = 0.000484
Step 400: objective = 0.000525
Step 600: objective = 0.000536
Step 800: objective = 0.000540
Step 1000: objective = 0.000544
Step 1200: objective = 0.000545
Step 1400: objective = 0.000544
Step 1600: objective = 0.000546
Step 1800: objective = 0.000548
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002164
Step 200: objective = 0.000741
Step 400: objective = 0.000798
Step 600: objective = 0.000813
Step 800: objective = 0.000819
Step 1000: objective = 0.000819
Step 1200: objective = 0.000820
Step 1400: objective = 0.000826
Step 1600: objective = 0.000816
Step 1800: objective = 0.000822
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002040
Step 200: objective = 0.000696
Step 400: objective = 0.000745
Step 600: objective = 0.000758
Step 800: objective = 0.000763
Step 1000: objective = 0.000766
Step 1200: objective = 0.000763
Step 1400: objective = 0.000757
Step 1600: objective = 0.000769
Step 1800: objective = 0.000770
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002004
Step 200: objective = 0.000795
Step 400: objective = 0.000845
Step 600: objective = 0.000856
Step 800: objective = 0.000865
Step 1000: objective = 0.000866
Step 1200: objective = 0.000869
Step 1400: objective = 0.000869
Step 1600: objective = 0.000868
Step 1800: objective = 0.000867
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002105
Step 200: objective = 0.000825
Step 400: objective = 0.000885
Step 600: objective = 0.000900
Step 800: objective = 0.000907
Step 1000: objective = 0.000910
Step 1200: objective = 0.000912
Step 1400: objective = 0.000913
Step 1600: objective = 0.000871
Step 1800: objective = 0.000910
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.003251
Step 200: objective = 0.000351
Step 400: objective = 0.000462
Step 600: objective = 0.000486
Step 800: objective = 0.000497
Step 1000: objective = 0.000502
Step 1200: objective = 0.000506
Step 1400: objective = 0.000508
Step 1600: objective = 0.000510
Step 1800: objective = 0.000511
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.003239
Step 200: objective = 0.000611
Step 400: objective = 0.000727
Step 600: objective = 0.000754
Step 800: objective = 0.000766
Step 1000: objective = 0.000772
Step 1200: objective = 0.000776
Step 1400: objective = 0.000776
Step 1600: objective = 0.000780
Step 1800: objective = 0.000780
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.003312
Step 200: objective = 0.000409
Step 400: objective = 0.000490
Step 600: objective = 0.000509
Step 800: objective = 0.000519
Step 1000: objective = 0.000523
Step 1200: objective = 0.000525
Step 1400: objective = 0.000526
Step 1600: objective = 0.000528
Step 1800: objective = 0.000529
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.003144
Step 200: objective = 0.000695
Step 400: objective = 0.000755
Step 600: objective = 0.000774
Step 800: objective = 0.000782
Step 1000: objective = 0.000786
Step 1200: objective = 0.000788
Step 1400: objective = 0.000791
Step 1600: objective = 0.000792
Step 1800: objective = 0.000793
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.003207
Step 200: objective = 0.000688
Step 400: objective = 0.000754
Step 600: objective = 0.000772
Step 800: objective = 0.000778
Step 1000: objective = 0.000783
Step 1200: objective = 0.000786
Step 1400: objective = 0.000788
Step 1600: objective = 0.000786
Step 1800: objective = 0.000789
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002956
Step 200: objective = 0.000671
Step 400: objective = 0.000720
Step 600: objective = 0.000734
Step 800: objective = 0.000738
Step 1000: objective = 0.000743
Step 1200: objective = 0.000745
Step 1400: objective = 0.000746
Step 1600: objective = 0.000747
Step 1800: objective = 0.000748
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002715
Step 200: objective = 0.000560
Step 400: objective = 0.000575
Step 600: objective = 0.000580
Step 800: objective = 0.000582
Step 1000: objective = 0.000584
Step 1200: objective = 0.000585
Step 1400: objective = 0.000585
Step 1600: objective = 0.000586
Step 1800: objective = 0.000585
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002706
Step 200: objective = 0.000438
Step 400: objective = 0.000461
Step 600: objective = 0.000468
Step 800: objective = 0.000470
Step 1000: objective = 0.000471
Step 1200: objective = 0.000472
Step 1400: objective = 0.000473
Step 1600: objective = 0.000469
Step 1800: objective = 0.000472
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002894
Step 200: objective = 0.000288
Step 400: objective = 0.000318
Step 600: objective = 0.000327
Step 800: objective = 0.000330
Step 1000: objective = 0.000332
Step 1200: objective = 0.000333
Step 1400: objective = 0.000334
Step 1600: objective = 0.000335
Step 1800: objective = 0.000335
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.003111
Step 200: objective = 0.000275
Step 400: objective = 0.000327
Step 600: objective = 0.000340
Step 800: objective = 0.000346
Step 1000: objective = 0.000350

                Sharpes  Sortinos      Vars     Cvars  MeanReturn
Equal weights  0.992128  1.638012 -0.007870 -0.013568    0.000404
Risk parity    0.987706  1.632170 -0.007839 -0.013510    0.000401
Return + CVaR  0.818067  1.269157 -0.008344 -0.013947    0.000324

In [76]:
def sample(sorted_returns, amount):
    res = []
    n = len(sorted_returns)
    for _ in range(amount):
        u = np.random.uniform()
        for i,val in enumerate(sorted_returns):
            if i >= n*u:
                res.append(val)
                break
    return res

def sample_combined(sorted_returns, amount, weights):
    # weights: (N)
    # sorted returns: (T, N) array
    final = np.zeros_like(sorted_returns)
    for i in range(sorted_returns.shape[1]):
        final[:,i] = sample(sorted_returns[:,i], amount)
    
    return final @ weights

In [77]:
df = block_bootstrap(200, returns_all)
df

Step 0: objective = -0.003101
Step 200: objective = 0.000059
Step 400: objective = 0.000129
Step 600: objective = 0.000149
Step 800: objective = 0.000159
Step 1000: objective = 0.000162
Step 1200: objective = 0.000165
Step 1400: objective = 0.000162
Step 1600: objective = 0.000164
Step 1800: objective = 0.000169
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002597
Step 200: objective = 0.000866
Step 400: objective = 0.001011
Step 600: objective = 0.001039
Step 800: objective = 0.001048
Step 1000: objective = 0.001052
Step 1200: objective = 0.001058
Step 1400: objective = 0.001060
Step 1600: objective = 0.001061
Step 1800: objective = 0.001062
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002831
Step 200: objective = -0.000165
Step 400: objective = -0.000080
Step 600: objective = -0.000062
Step 800: objective = -0.000054
Step 1000: objective = -0.000049
Step 1200: objective = -0.000050
Step 1400: objective = -0.000046
Step 1600: objective = -0.000048
Step 1800: objective = -0.000051
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002028
Step 200: objective = 0.001739
Step 400: objective = 0.002003
Step 600: objective = 0.002039
Step 800: objective = 0.002053
Step 1000: objective = 0.002058
Step 1200: objective = 0.002062
Step 1400: objective = 0.002061
Step 1600: objective = 0.002065
Step 1800: objective = 0.002067
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001387
Step 200: objective = 0.001282
Step 400: objective = 0.001360
Step 600: objective = 0.001379
Step 800: objective = 0.001385
Step 1000: objective = 0.001391
Step 1200: objective = 0.001389
Step 1400: objective = 0.001394
Step 1600: objective = 0.001386
Step 1800: objective = 0.001395
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001508
Step 200: objective = 0.001723
Step 400: objective = 0.001887
Step 600: objective = 0.001912
Step 800: objective = 0.001919
Step 1000: objective = 0.001928
Step 1200: objective = 0.001918
Step 1400: objective = 0.001934
Step 1600: objective = 0.001936
Step 1800: objective = 0.001934
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.003866
Step 200: objective = 0.000628
Step 400: objective = 0.000823
Step 600: objective = 0.000865
Step 800: objective = 0.000877
Step 1000: objective = 0.000889
Step 1200: objective = 0.000890
Step 1400: objective = 0.000899
Step 1600: objective = 0.000902
Step 1800: objective = 0.000901
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001551
Step 200: objective = 0.001235
Step 400: objective = 0.001359
Step 600: objective = 0.001388
Step 800: objective = 0.001399
Step 1000: objective = 0.001403
Step 1200: objective = 0.001408
Step 1400: objective = 0.001410
Step 1600: objective = 0.001411
Step 1800: objective = 0.001412
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002721
Step 200: objective = 0.000147
Step 400: objective = 0.000225
Step 600: objective = 0.000239
Step 800: objective = 0.000247
Step 1000: objective = 0.000251
Step 1200: objective = 0.000253
Step 1400: objective = 0.000252
Step 1600: objective = 0.000250
Step 1800: objective = 0.000253
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.003099
Step 200: objective = -0.000025
Step 400: objective = 0.000036
Step 600: objective = 0.000052
Step 800: objective = 0.000059
Step 1000: objective = 0.000063
Step 1200: objective = 0.000065
Step 1400: objective = 0.000062
Step 1600: objective = 0.000064
Step 1800: objective = 0.000068
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002363
Step 200: objective = 0.000637
Step 400: objective = 0.000717
Step 600: objective = 0.000730
Step 800: objective = 0.000741
Step 1000: objective = 0.000744
Step 1200: objective = 0.000747
Step 1400: objective = 0.000746
Step 1600: objective = 0.000749
Step 1800: objective = 0.000750
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.003171
Step 200: objective = -0.000234
Step 400: objective = -0.000185
Step 600: objective = -0.000171
Step 800: objective = -0.000165
Step 1000: objective = -0.000164
Step 1200: objective = -0.000162
Step 1400: objective = -0.000159
Step 1600: objective = -0.000158
Step 1800: objective = -0.000185
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001873
Step 200: objective = 0.001036
Step 400: objective = 0.001102
Step 600: objective = 0.001117
Step 800: objective = 0.001126
Step 1000: objective = 0.001130
Step 1200: objective = 0.001131
Step 1400: objective = 0.001131
Step 1600: objective = 0.001134
Step 1800: objective = 0.001134
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001159
Step 200: objective = 0.001482
Step 400: objective = 0.001573
Step 600: objective = 0.001593
Step 800: objective = 0.001590
Step 1000: objective = 0.001598
Step 1200: objective = 0.001602
Step 1400: objective = 0.001590
Step 1600: objective = 0.001599
Step 1800: objective = 0.001580
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001404
Step 200: objective = 0.001645
Step 400: objective = 0.001773
Step 600: objective = 0.001801
Step 800: objective = 0.001812
Step 1000: objective = 0.001818
Step 1200: objective = 0.001821
Step 1400: objective = 0.001823
Step 1600: objective = 0.001824
Step 1800: objective = 0.001810
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.004354
Step 200: objective = -0.000546
Step 400: objective = -0.000474
Step 600: objective = -0.000452
Step 800: objective = -0.000444
Step 1000: objective = -0.000440
Step 1200: objective = -0.000462
Step 1400: objective = -0.000435
Step 1600: objective = -0.000438
Step 1800: objective = -0.000433
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001256
Step 200: objective = 0.001022
Step 400: objective = 0.001034
Step 600: objective = 0.001040
Step 800: objective = 0.001042
Step 1000: objective = 0.001044
Step 1200: objective = 0.001044
Step 1400: objective = 0.001045
Step 1600: objective = 0.001039
Step 1800: objective = 0.001044
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001585
Step 200: objective = 0.001572
Step 400: objective = 0.001701
Step 600: objective = 0.001732
Step 800: objective = 0.001743
Step 1000: objective = 0.001749
Step 1200: objective = 0.001752
Step 1400: objective = 0.001754
Step 1600: objective = 0.001752
Step 1800: objective = 0.001755
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002981
Step 200: objective = -0.000202
Step 400: objective = -0.000151
Step 600: objective = -0.000138
Step 800: objective = -0.000132
Step 1000: objective = -0.000130
Step 1200: objective = -0.000128
Step 1400: objective = -0.000128
Step 1600: objective = -0.000131
Step 1800: objective = -0.000125
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001364
Step 200: objective = 0.001268
Step 400: objective = 0.001331
Step 600: objective = 0.001355
Step 800: objective = 0.001358
Step 1000: objective = 0.001366
Step 1200: objective = 0.001370
Step 1400: objective = 0.001371
Step 1600: objective = 0.001371
Step 1800: objective = 0.001373
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001610
Step 200: objective = 0.001746
Step 400: objective = 0.001883
Step 600: objective = 0.001908
Step 800: objective = 0.001930
Step 1000: objective = 0.001939
Step 1200: objective = 0.001943
Step 1400: objective = 0.001945
Step 1600: objective = 0.001942
Step 1800: objective = 0.001940
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.003740
Step 200: objective = 0.000476
Step 400: objective = 0.000559
Step 600: objective = 0.000572
Step 800: objective = 0.000580
Step 1000: objective = 0.000584
Step 1200: objective = 0.000586
Step 1400: objective = 0.000587
Step 1600: objective = 0.000590
Step 1800: objective = 0.000589
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001842
Step 200: objective = 0.000834
Step 400: objective = 0.000870
Step 600: objective = 0.000881
Step 800: objective = 0.000885
Step 1000: objective = 0.000888
Step 1200: objective = 0.000888
Step 1400: objective = 0.000890
Step 1600: objective = 0.000891
Step 1800: objective = 0.000890
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001594
Step 200: objective = 0.001043
Step 400: objective = 0.001174
Step 600: objective = 0.001197
Step 800: objective = 0.001206
Step 1000: objective = 0.001208
Step 1200: objective = 0.001212
Step 1400: objective = 0.001209
Step 1600: objective = 0.001213
Step 1800: objective = 0.001216
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.004446
Step 200: objective = 0.000192
Step 400: objective = 0.000314
Step 600: objective = 0.000343
Step 800: objective = 0.000354
Step 1000: objective = 0.000355
Step 1200: objective = 0.000361
Step 1400: objective = 0.000365
Step 1600: objective = 0.000364
Step 1800: objective = 0.000366
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.003522
Step 200: objective = -0.000646
Step 400: objective = -0.000607
Step 600: objective = -0.000602
Step 800: objective = -0.000595
Step 1000: objective = -0.000591
Step 1200: objective = -0.000590
Step 1400: objective = -0.000595
Step 1600: objective = -0.000589
Step 1800: objective = -0.000589
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.004147
Step 200: objective = 0.000083
Step 400: objective = 0.000174
Step 600: objective = 0.000196
Step 800: objective = 0.000207
Step 1000: objective = 0.000212
Step 1200: objective = 0.000216
Step 1400: objective = 0.000218
Step 1600: objective = 0.000215
Step 1800: objective = 0.000220
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.004688
Step 200: objective = -0.001069
Step 400: objective = -0.000999
Step 600: objective = -0.000980
Step 800: objective = -0.000972
Step 1000: objective = -0.000971
Step 1200: objective = -0.000967
Step 1400: objective = -0.000964
Step 1600: objective = -0.000971
Step 1800: objective = -0.000962
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002343
Step 200: objective = 0.000667
Step 400: objective = 0.000751
Step 600: objective = 0.000768
Step 800: objective = 0.000777
Step 1000: objective = 0.000780
Step 1200: objective = 0.000783
Step 1400: objective = 0.000783
Step 1600: objective = 0.000786
Step 1800: objective = 0.000773
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001715
Step 200: objective = 0.001342
Step 400: objective = 0.001580
Step 600: objective = 0.001614
Step 800: objective = 0.001626
Step 1000: objective = 0.001631
Step 1200: objective = 0.001635
Step 1400: objective = 0.001635
Step 1600: objective = 0.001637
Step 1800: objective = 0.001632
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.004109
Step 200: objective = -0.000299
Step 400: objective = -0.000283
Step 600: objective = -0.000271
Step 800: objective = -0.000266
Step 1000: objective = -0.000261
Step 1200: objective = -0.000258
Step 1400: objective = -0.000255
Step 1600: objective = -0.000256
Step 1800: objective = -0.000254
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001679
Step 200: objective = 0.001351
Step 400: objective = 0.001559
Step 600: objective = 0.001588
Step 800: objective = 0.001600
Step 1000: objective = 0.001604

                Sharpes  Sortinos      Vars     Cvars  MeanReturn
Equal weights  1.051824  1.738873 -0.007703 -0.013041    0.000412
Risk parity    1.039199  1.717977 -0.007680 -0.012998    0.000405
Return + CVaR  0.583604  0.900634 -0.008890 -0.014768    0.000243

Test bear market conditions for all approaches

In [91]:

val_returns_total = []
train_returns_total = []

for df in filtered_dfs:
    df_datetime = df.copy()
    df_datetime["Date"] = pd.to_datetime(df_datetime["Date"])
    train = df_datetime[
        (df_datetime["Date"] >= pd.to_datetime("2024-01-01"))
        & (df_datetime["Date"] <= pd.to_datetime("2025-01-01"))]
    val = df_datetime[
        (df_datetime["Date"] >= pd.to_datetime("2025-01-01"))
        & (df_datetime["Date"] <= pd.to_datetime("2025-04-01"))
    ]

    train_returns = train["Close"].pct_change().values[1:]
    val_returns = val["Close"].pct_change().values[1:]

    print(len(train_returns))
    print(len(val_returns))
    print()

    val_returns_total.append(val_returns)
    train_returns_total.append(train_returns)
    
train_returns_total = np.array(train_returns_total).T # shape (num_days, N = num_assets)
val_returns_total = np.array(val_returns_total).T

cov = np.cov(train_returns_total, rowvar=False)

w_opt = gradient_reduced(train_returns_total, cov)
w_rp = gradient_risk_parity(cov)

(
    var_alpha_opt, cvar_opt, sharpe_opt, sortino_opt, cumulative_returns_opt, mean_return_opt
) = perform_validation(w_opt, val_returns_total)

(
    var_alpha_rp, cvar_rp, sharpe_rp, sortino_rp, cumulative_returns_rp, mean_return_rp
) = perform_validation(w_rp, val_returns_total)

(
    var_alpha_eqw, cvar_eqw, sharpe_eqw, sortino_eqw, cumulative_returns_eqw, mean_return_eqw
) = perform_validation(np.ones(N) / N, val_returns_total)

df = pd.DataFrame({
    "Sharpe": [sharpe_opt, sharpe_eqw, sharpe_rp],
    "Sortino": [sortino_opt, sortino_eqw, sortino_rp],
    "Var": [var_alpha_opt, var_alpha_eqw, var_alpha_rp],
    "Cvar": [cvar_opt, cvar_eqw, cvar_rp],
    "Mean return": [mean_return_opt, mean_return_eqw, mean_return_rp],
}, index=["Optimized weights", "Equal weights", "Risk parity weights"])
df

249
63

249
63

249
63

249
63

249
63

249
63

249
63

Step 0: objective = -0.001718
Step 200: objective = 0.001520
Step 400: objective = 0.001645
Step 600: objective = 0.001674
Step 800: objective = 0.001680
Step 1000: objective = 0.001691
Step 1200: objective = 0.001695
Step 1400: objective = 0.001697
Step 1600: objective = 0.001698
Step 1800: objective = 0.001700
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000

                       Sharpe   Sortino       Var      Cvar  Mean return
Optimized weights    0.845078  1.890344 -0.010094 -0.013804     0.000389
Equal weights        0.628597  1.289585 -0.007833 -0.010334     0.000231
Risk parity weights  0.630959  1.295210 -0.007836 -0.010340     0.000231

In [96]:
fig = go.Figure()
L = list(range(len(cumulative_returns_opt)))
fig.add_trace(go.Scatter(x=L, y=cumulative_returns_eqw, name="equal weights"))
fig.add_trace(go.Scatter(x=L, y=cumulative_returns_rp, name="risk parity weights"))
fig.add_trace(go.Scatter(x=L, y=cumulative_returns_opt, name="optimized weights"))
fig.show()

In [97]:

val_returns_total = []
train_returns_total = []

for df in filtered_dfs:
    df_datetime = df.copy()
    df_datetime["Date"] = pd.to_datetime(df_datetime["Date"])
    train = df_datetime[
        (df_datetime["Date"] >= pd.to_datetime("2019-02-05"))
        & (df_datetime["Date"] <= pd.to_datetime("2020-02-12"))]
    val = df_datetime[
        (df_datetime["Date"] >= pd.to_datetime("2020-02-12"))
        & (df_datetime["Date"] <= pd.to_datetime("2020-04-03"))
    ]

    train_returns = train["Close"].pct_change().values[1:]
    val_returns = val["Close"].pct_change().values[1:]

    print(len(train_returns))
    print(len(val_returns))
    print()

    val_returns_total.append(val_returns)
    train_returns_total.append(train_returns)
    
train_returns_total = np.array(train_returns_total).T # shape (num_days, N = num_assets)
val_returns_total = np.array(val_returns_total).T

cov = np.cov(train_returns_total, rowvar=False)

w_opt = gradient_reduced(train_returns_total, cov)
w_rp = gradient_risk_parity(cov)

(
    var_alpha_opt, cvar_opt, sharpe_opt, sortino_opt, cumulative_returns_opt, mean_return_opt
) = perform_validation(w_opt, val_returns_total)

(
    var_alpha_rp, cvar_rp, sharpe_rp, sortino_rp, cumulative_returns_rp, mean_return_rp
) = perform_validation(w_rp, val_returns_total)

(
    var_alpha_eqw, cvar_eqw, sharpe_eqw, sortino_eqw, cumulative_returns_eqw, mean_return_eqw
) = perform_validation(np.ones(N) / N, val_returns_total)

df = pd.DataFrame({
    "Sharpe": [sharpe_opt, sharpe_eqw, sharpe_rp],
    "Sortino": [sortino_opt, sortino_eqw, sortino_rp],
    "Var": [var_alpha_opt, var_alpha_eqw, var_alpha_rp],
    "Cvar": [cvar_opt, cvar_eqw, cvar_rp],
    "Mean return": [mean_return_opt, mean_return_eqw, mean_return_rp],
}, index=["Optimized weights", "Equal weights", "Risk parity weights"])
df

252
37

252
37

252
37

252
37

252
37

252
37

252
37

Step 0: objective = -0.001553
Step 200: objective = 0.001476
Step 400: objective = 0.001595
Step 600: objective = 0.001624
Step 800: objective = 0.001619
Step 1000: objective = 0.001626
Step 1200: objective = 0.001640
Step 1400: objective = 0.001628
Step 1600: objective = 0.001641
Step 1800: objective = 0.001641
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000

                       Sharpe   Sortino       Var      Cvar  Mean return
Optimized weights   -2.937295 -4.752442 -0.032358 -0.046036    -0.004243
Equal weights       -3.476657 -7.111435 -0.038604 -0.055634    -0.005743
Risk parity weights -3.476951 -7.110746 -0.038571 -0.055617    -0.005742

In [98]:
fig = go.Figure()
L = list(range(len(cumulative_returns_opt)))
fig.add_trace(go.Scatter(x=L, y=cumulative_returns_eqw, name="equal weights"))
fig.add_trace(go.Scatter(x=L, y=cumulative_returns_rp, name="risk parity weights"))
fig.add_trace(go.Scatter(x=L, y=cumulative_returns_opt, name="optimized weights"))
fig.show()